classdef KeyPressedEventData < event.EventData
    
    properties
        Key
        Character
        ShiftDown
        AltDown
        AltGraphDown
        ControlDown
        MetaDown
    end
    
    properties ( Constant)
        keys = { '', ...
            '', '', '', '', '', '', '', 'backspace', 'tab', 'return', ...
            '', '', '', '', '', 'shift', 'control', 'alt', '', 'capslock', ...
            '', '', '', '', '', '', 'escape', '', '', '', ...
            '', 'space', '', '', '', '', 'leftarrow', 'uparrow', 'rightarrow', 'downarrow', ...
            '', '', '', 'comma', 'hyphen', 'period', 'slash', '', '', '', ...
            '', '', '', '', '', '', '', '', 'semicolon', '', ...
            'equal', '', '', '', '', '', '', '', '', '', ...
            '', '', '', '', '', '', '', '', '', '', ...
            '', '', '', '', '', '', '', '', '', '', ...
            'leftbracket', 'backslash', 'rightbracket', '', '', '', '', '', '', '', ...
            '', '', '', '', '', '', '', '', '', '', ...
            '', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', ...
            'f10', 'f11', 'f12', '', '', '', '', '', '', '', ...
            '', '', '', '', '', '', '', '', '', '', ...
            '', '', '', '', '', '', '', '', '', '', ...
            '', '', '', '', '', '', 'command', '', '', '', ...
            '', '', '', '', '', '', '', '', '', '', ...
            '', '', '', '', '', '', '', '', '', '', ...
            '', '', '', '', '', '', '', '', '', '', ...
            '', 'backquote', '', '', '', '', '', '', '', '', ...
            '', '', '', '', '', '', '', '', '', '', ...
            '', '', '', '', '', '', '', '', '', '', ...
            '', 'quote', '', '', '', '', '', '', '', '', ...
            '', '', '', '', '', '', '', '', '', '', ...
            '', '', '', '', '', '', '', '', '', '', ...
            '', '', '', '', '', '', '', '', '', '', ...
            '', '', '', '', '', '', '', '', '', '', ...
            '', '', '', '', '', '', '', '', '', '', ...
            '', '', '', '', '', '', '', '', '', '', ...
            '', '', '', '', '', '', '', '', '', '', ...
            '', '', '', '', '', '', '', '', '', '', ...
        };
    end
    
    methods
        function self = KeyPressedEventData(evt)
            self.Character = evt.KeyChar;
            self.Key = self.keys{evt.KeyCode + 1};
            self.ShiftDown = evt.ShiftDown;
            self.AltDown = evt.AltDown;
            self.AltGraphDown = evt.AltGraphDown;
            self.ControlDown = evt.ControlDown;
            self.MetaDown = evt.MetaDown;
        end
    end
    
end
